### ISSUE TITLE
Cần hỗ trợ unicode (tiếng Nhật)

### ISSUE THREAD

**Issue by vuhung** [cuongpv93/codeigniter#3]
Trang sau: 
http://cuongpham.freevnn.com/cuongpv/school/giaovien/show

Cần hỗ trợ tiếng Unicode/Nhật cho mọi trang 

Cho các chức năng: add new, edit 

![image](https://cloud.githubusercontent.com/assets/332742/18739368/521f7fe2-80cd-11e6-9566-2a4b94367bb8.png)

**Comment by vuhung** [comment]
![image](https://cloud.githubusercontent.com/assets/332742/18739505/46741d0a-80ce-11e6-85a4-1d93fb09d4bc.png)

URL: http://cuongpham.freevnn.com/cuongpv/school/giaovien/show

**Comment by cuongpv93** [comment]
em đã cài sang utf 8 rồi
