### ISSUE TITLE
Tự free test lại chương trình của mình

### ISSUE THREAD

**Issue by vuhung** [cuongpv93/codeigniter#6]
Tự free test lại chương trình của mình:
1. Các luồng chính
2. Các dạng dữ liệu đầu vào (email, password)
3. Các thông báo lỗi (popup hay label (đỏ))
4. Lỗi khi hover mouse trên button (chưa fix từ tuần trước)

**Comment by cuongpv93** [comment]
Em đã test và sửa lỗi, em thay giao diện băng bootstrap rồi nên không còn lỗi hover mouse nữa

**Comment by vuhung** [comment]
Ok. Lần sau lại dùng bootstrap tiếp :)
Đứng trên vai người khổng lồ.

Cố học cách dùng framework có sẵn.

No excuse for being brief on mobile.
